### ISSUE TITLE
Cut's the text and does not output the full transcription

### ISSUE THREAD

**Issue by metaldaniel** [ShmuelRonen/hebrew_whisper#1]
So thanks for this, I ran this from my laptop (CPU) and on AWS (GPU) and in both of these instances the text displayed is cut after the first paragraph it seems. It brings like 10% of the text.

I did not yet have time to debug this, hopefully you see this and know how to fix it quicker :)
Tried with wav and mp3 files, same result.

(Bonus) would be nice if Gradio can display Hebrew as LTR.

**Comment by metaldaniel** [comment]
A bit more details - my file is 4:22 - but it processed only 3 chunks - with 30 sec / chunk it should have been more.
+ The final transcription is not from the first 1:30 min, but rather has the first ~30sec and then text from the middle/end of the clip.
So there's an issue with chucking the reassembling the text back.

**Comment by ShmuelRonen** [comment]
Since I can't reproduce this problem on my computer. Send the CMD log so I can maybe understand more about what the problem is.
