### ISSUE TITLE
הוספת תכונות

### ISSUE THREAD

**Issue by start-life** [ShmuelRonen/hebrew_whisper#3]
נשמח אם תוסיף תכונות יצוא כקובץ טקסט או כקובץ לכתוביות

**Comment by ShmuelRonen** [comment]
בעבודה

**Comment by ShmuelRonen** [comment]
העדכון בוצע הבוקר

**Comment by start-life** [comment]
זה מעולה רק רציתי להציע אם יהיה אפשר פשוט להוריד את זה כקובץ טקסט או לשמור את זה כקובץ כתוביות אבל שיהיה אפשר לשמור את זה כקובץ כי כרגע צריך לעשות העתק הדבק לכל החלון של הטקסט וזה סתם פשוט יותר מדי מורכב תודה

**Comment by ShmuelRonen** [comment]
קובץ הכתוביות נשמר בתקיית output כ xxx.srt
את קובץ הטקסט הרגיל צריך עדיין להעתיק מהמסך

**Comment by ShmuelRonen** [comment]
הוספתי את תכונת השמירה בתקיית output
קובץ טקסט ישמר כ result.txt
קובץ כתוביות יישמר כ output.srt
