### ISSUE TITLE
כל הפעלה הוא מוריד חבילות PIP מחדש

### ISSUE THREAD

**Issue by start-life** [ShmuelRonen/hebrew_whisper#4]
זה היומן

Updating the repository...
Already up to date.
Repository updated.
Installing requirements...
Looking in indexes: https://download.pytorch.org/whl/cu118, https://pypi.ngc.nvidia.com
Requirement already satisfied: torch in c:\zxcv\hebrew_whisper\venv\lib\site-packages (2.2.2+cu118)
Requirement already satisfied: torchvision in c:\zxcv\hebrew_whisper\venv\lib\site-packages (0.17.2+cu118)
Requirement already satisfied: torchaudio in c:\zxcv\hebrew_whisper\venv\lib\site-packages (2.2.2+cu118)
Requirement already satisfied: filelock in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torch) (4.8.0)
Requirement already satisfied: sympy in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torch) (2024.3.1)
Requirement already satisfied: numpy in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torchvision) (1.26.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torchvision) (10.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from sympy->torch) (1.3.0)
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: gradio in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 1)) (4.19.1)
Requirement already satisfied: numpy in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 2)) (1.26.3)
Requirement already satisfied: transformers in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 3)) (4.39.3)
Requirement already satisfied: librosa in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 4)) (0.10.1)
Requirement already satisfied: soundfile in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 5)) (0.12.1)
Requirement already satisfied: tqdm in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 6)) (4.66.2)
Requirement already satisfied: googletrans==4.0.0-rc1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 8)) (4.0.0rc1)
Requirement already satisfied: openai-whisper in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 9)) (20231117)
Requirement already satisfied: nltk in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from -r requirements.txt (line 10)) (3.8.1)
Requirement already satisfied: httpx==0.13.3 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (0.13.3)
Requirement already satisfied: certifi in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (2024.2.2)
Requirement already satisfied: hstspreload in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (2024.4.1)
Requirement already satisfied: sniffio in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (1.3.1)
Requirement already satisfied: chardet==3.* in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (3.0.4)
Requirement already satisfied: idna==2.* in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (2.10)
Requirement already satisfied: rfc3986<2,>=1.3 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (1.5.0)
Requirement already satisfied: httpcore==0.9.* in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (0.9.1)
Requirement already satisfied: h11<0.10,>=0.8 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (0.9.0)
Requirement already satisfied: h2==3.* in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1->-r requirements.txt (line 8)) (3.0.0)
Requirement already satisfied: aiofiles<24.0,>=22.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (5.3.0)
Requirement already satisfied: fastapi in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.110.1)
Requirement already satisfied: ffmpy in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.3.2)
Requirement already satisfied: gradio-client==0.10.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.10.0)
Requirement already satisfied: huggingface-hub>=0.19.3 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.22.2)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (6.4.0)
Requirement already satisfied: jinja2<4.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: markupsafe~=2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: matplotlib~=3.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (3.8.4)
Requirement already satisfied: orjson~=3.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (3.10.0)
Requirement already satisfied: packaging in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (24.0)
Requirement already satisfied: pandas<3.0,>=1.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (2.2.1)
Requirement already satisfied: pillow<11.0,>=8.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (10.2.0)
Requirement already satisfied: pydantic>=2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (2.6.4)
Requirement already satisfied: pydub in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.9 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.0.9)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: ruff>=0.1.7 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.3.5)
Requirement already satisfied: semantic-version~=2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (2.10.0)
Requirement already satisfied: tomlkit==0.12.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: typer[all]<1.0,>=0.9 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: uvicorn>=0.14.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio->-r requirements.txt (line 1)) (0.29.0)
Requirement already satisfied: fsspec in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio-client==0.10.0->gradio->-r requirements.txt (line 1)) (2024.3.1)
Requirement already satisfied: websockets<12.0,>=10.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from gradio-client==0.10.0->gradio->-r requirements.txt (line 1)) (11.0.3)
Requirement already satisfied: filelock in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from transformers->-r requirements.txt (line 3)) (3.9.0)
Requirement already satisfied: regex!=2019.12.17 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from transformers->-r requirements.txt (line 3)) (2023.12.25)
Requirement already satisfied: requests in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from transformers->-r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from transformers->-r requirements.txt (line 3)) (0.15.2)
Requirement already satisfied: safetensors>=0.4.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from transformers->-r requirements.txt (line 3)) (0.4.2)
Requirement already satisfied: audioread>=2.1.9 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (3.0.1)
Requirement already satisfied: scipy>=1.2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (1.13.0)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (1.4.1.post1)
Requirement already satisfied: joblib>=0.14 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (1.3.2)
Requirement already satisfied: decorator>=4.3.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (5.1.1)
Requirement already satisfied: numba>=0.51.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (0.59.1)
Requirement already satisfied: pooch>=1.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (1.8.1)
Requirement already satisfied: soxr>=0.3.2 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (0.3.7)
Requirement already satisfied: lazy-loader>=0.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (0.4)
Requirement already satisfied: msgpack>=1.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from librosa->-r requirements.txt (line 4)) (1.0.8)
Requirement already satisfied: cffi>=1.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from soundfile->-r requirements.txt (line 5)) (1.16.0)
Requirement already satisfied: colorama in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from tqdm->-r requirements.txt (line 6)) (0.4.6)
Requirement already satisfied: torch in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from openai-whisper->-r requirements.txt (line 9)) (2.2.2+cu118)
Requirement already satisfied: more-itertools in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from openai-whisper->-r requirements.txt (line 9)) (10.2.0)
Requirement already satisfied: tiktoken in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from openai-whisper->-r requirements.txt (line 9)) (0.6.0)
Requirement already satisfied: click in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from nltk->-r requirements.txt (line 10)) (8.1.7)
Requirement already satisfied: jsonschema>=3.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from altair<6.0,>=4.2.0->gradio->-r requirements.txt (line 1)) (4.21.1)
Requirement already satisfied: toolz in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from altair<6.0,>=4.2.0->gradio->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: pycparser in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from cffi>=1.0->soundfile->-r requirements.txt (line 5)) (2.22)
Requirement already satisfied: contourpy>=1.0.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from matplotlib~=3.0->gradio->-r requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from matplotlib~=3.0->gradio->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from matplotlib~=3.0->gradio->-r requirements.txt (line 1)) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from matplotlib~=3.0->gradio->-r requirements.txt (line 1)) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from matplotlib~=3.0->gradio->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from matplotlib~=3.0->gradio->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from numba>=0.51.0->librosa->-r requirements.txt (line 4)) (0.42.0)
Requirement already satisfied: pytz>=2020.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from pandas<3.0,>=1.0->gradio->-r requirements.txt (line 1)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from pandas<3.0,>=1.0->gradio->-r requirements.txt (line 1)) (2024.1)
Requirement already satisfied: platformdirs>=2.5.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from pooch>=1.0->librosa->-r requirements.txt (line 4)) (4.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from pydantic>=2.0->gradio->-r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from pydantic>=2.0->gradio->-r requirements.txt (line 1)) (2.16.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from requests->transformers->-r requirements.txt (line 3)) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from requests->transformers->-r requirements.txt (line 3)) (2.2.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from scikit-learn>=0.20.0->librosa->-r requirements.txt (line 4)) (3.4.0)
WARNING: typer 0.12.1 does not provide the extra 'all'
Requirement already satisfied: shellingham>=1.3.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from typer[all]<1.0,>=0.9->gradio->-r requirements.txt (line 1)) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from typer[all]<1.0,>=0.9->gradio->-r requirements.txt (line 1)) (13.7.1)
Requirement already satisfied: starlette<0.38.0,>=0.37.2 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from fastapi->gradio->-r requirements.txt (line 1)) (0.37.2)
Requirement already satisfied: sympy in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torch->openai-whisper->-r requirements.txt (line 9)) (1.12)
Requirement already satisfied: networkx in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from torch->openai-whisper->-r requirements.txt (line 9)) (3.2.1)
Requirement already satisfied: attrs>=22.2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->-r requirements.txt (line 1)) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->-r requirements.txt (line 1)) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->-r requirements.txt (line 1)) (0.34.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->-r requirements.txt (line 1)) (0.18.0)
Requirement already satisfied: six>=1.5 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from rich>=10.11.0->typer[all]<1.0,>=0.9->gradio->-r requirements.txt (line 1)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from rich>=10.11.0->typer[all]<1.0,>=0.9->gradio->-r requirements.txt (line 1)) (2.17.2)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from starlette<0.38.0,>=0.37.2->fastapi->gradio->-r requirements.txt (line 1)) (4.3.0)
Requirement already satisfied: mpmath>=0.19 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from sympy->torch->openai-whisper->-r requirements.txt (line 9)) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in c:\zxcv\hebrew_whisper\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer[all]<1.0,>=0.9->gradio->-r requirements.txt (line 1)) (0.1.2)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirements installed.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.35s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by ShmuelRonen** [comment]
Fix packages reload issue
